### ISSUE TITLE
ImportError  QWebEngineView

### ISSUE THREAD

**Issue by chunlaiqingke** [sunshe35/PyQt6-codes#1]
Traceback (most recent call last):
  File "/Users/zhaojun/github/Python_Project/PyQt6-codes/Chapter06/qt_QWebEngineView.py", line 8, in <module>
    from PyQt6.QtWebEngineCore import QWebEnginePage
ImportError: dlopen(/Users/zhaojun/anaconda3/lib/python3.11/site-packages/PyQt6/QtWebEngineCore.abi3.so, 0x0002): Symbol not found: _qt_version_tag_6_6
  Referenced from: <E05FB3EE-5D42-3121-A19C-5CED50CB3132> /Users/zhaojun/anaconda3/lib/python3.11/site-packages/PyQt6/QtWebEngineCore.abi3.so
  Expected in:     <6238782E-D1AA-3245-81EF-2925BF1A4C96> /Users/zhaojun/anaconda3/lib/python3.11/site-packages/PyQt6/Qt6/lib/QtCore.framework/Versions/A/QtCore

请问这是为啥？

**Comment by sunshe35** [comment]
需要额外安装模块：PyQt6-WebEngine
```
pip install PyQt6-WebEngine
```
注意要和pyqt6版本相同，否则可能同样无法运行。
若还是出错，那就是py环境问题，建议重新搞个虚拟环境测试。
新环境下是不会有问题了。

**Comment by chunlaiqingke** [comment]
已经安装了，我的是因为版本有问题
