### ISSUE TITLE
Chapter05\qt_QListView.py的addAction报错，无法启动

### ISSUE THREAD

**Issue by fxbird** [sunshe35/PyQt6-codes#3]
你好，只要是调用了addAction就会报错，比如**Chapter05\qt_QListView.py**

`Traceback (most recent call last):
  File "E:\documents\programming\teach-self-code\python\pyqt\PySide6_PyQt6 rapid development and practice\Chapter05\qt_QListView.py", line 168, in <module>
    demo = QListViewDemo()
           ^^^^^^^^^^^^^^^

  File "E:\documents\programming\teach-self-code\python\pyqt\PySide6_PyQt6 rapid development and practice\Chapter05\qt_QListView.py", line 72, in __init__
    self.menu = self.generateMenu()
                ^^^^^^^^^^^^^^^^^^^
  File "E:\documents\programming\teach-self-code\python\pyqt\PySide6_PyQt6 rapid development and practice\Chapter05\qt_QListView.py", line 91, in generateMenu
    menu.addAction('增加',self.onAdd,QKeySequence(Qt.Modifier.CTRL|Qt.Key.Key_N))
TypeError: arguments did not match any overloaded call:
  addAction(self, icon: QIcon, text: str): argument 1 has unexpected type 'str'
  addAction(self, icon: QIcon, text: str, slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'str'
  addAction(self, icon: QIcon, text: str, shortcut: Union[QKeySequence, QKeySequence.StandardKey, str, int]): argument 1 has unexpected type 'str'
  addAction(self, icon: QIcon, text: str, shortcut: Union[QKeySequence, QKeySequence.StandardKey, str, int], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 1 has unexpected type 'str'
  addAction(self, text: str): too many arguments
  addAction(self, text: str, shortcut: Union[QKeySequence, QKeySequence.StandardKey, str, int]): argument 2 has unexpected type 'method'
  addAction(self, text: str, slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 3 has unexpected type 'QKeySequence'
  addAction(self, text: str, shortcut: Union[QKeySequence, QKeySequence.StandardKey, str, int], slot: PYQT_SLOT, type: Qt.ConnectionType = Qt.AutoConnection): argument 2 has unexpected type 'method'
  addAction(self, action: QAction): argument 1 has unexpected type 'str'`

请问这是什么原因？python版本是3.11.9

**Comment by sunshe35** [comment]
感谢反馈。
我看了下，确实存在这个问题。
原因是qt把参数顺序搞反了，原来是slot函数在shortcut之前，现在要放在shortcut后面。具体你结合报错信息以及参数信息就能看出来。
这个是官方的原因，没办法，需要自己做相应调整。
调整后的结果如下(??是乱码不能显示中文，请忽略这个错误)，其他类似报错也参照这种方式处理：
```python
    def generateMenu(self):
        menu = QMenu(self)
        menu.addAction('??',QKeySequence(Qt.Modifier.CTRL|Qt.Key.Key_N),self.onAdd)
        menu.addAction('??',QKeySequence(Qt.Modifier.CTRL|Qt.Key.Key_I),self.onInsert)
        menu.addAction(QIcon("images/close.png"),'??',QKeySequence(Qt.Modifier.CTRL|Qt.Key.Key_D),self.onDelete)
        menu.addSeparator()
        menu.addAction('??',QKeySequence(Qt.Modifier.CTRL|Qt.Key.Key_A), self.onSelectAll)
        menu.addAction('????',QKeySequence(Qt.Modifier.CTRL|Qt.Key.Key_R),self.onSelectClear)
        menu.addAction('????',self.onSelectOutput)
        menu.addSeparator()
        # menu.addAction(self.actionHelp)
        return menu
```

**Comment by sunshe35** [comment]
很奇怪的是pyside6不需要修改顺序就可以运行，看了下qt官方，c++没这些参数。是pyqt和pyside各自整活儿。

**Comment by fxbird** [comment]
确实是这样，把slot函数放后面就好了，谢谢。看来pyside和pyqt还是有些差别
